-- Sonic Healthcare USA Subsidiary Lab Test Codes
-- Generated: 2026-03-01
-- Sources: testmenu.com API, testmanual.sonichealthcareusa.com

-- ============================================
-- CLH — Clinical Labs of Hawaii
-- ============================================
INSERT INTO lab_test_codes (lab_id, test_name, order_code, lab_test_name, source) VALUES
('clh', 'CBC', '0360', 'CBC Complete Blood Count w/ Diff', 'testmenu.com/CLH'),
('clh', 'CMP', '2053', 'Comprehensive Metabolic Chemistry Panel', 'testmenu.com/CLH'),
('clh', 'BMP', '2048', 'Basic Metabolic Chemistry BMP Panel', 'testmenu.com/CLH'),
('clh', 'TSH', '0261', 'TSH', 'testmenu.com/CLH'),
('clh', 'Free T3', '2554', 'T3, Free', 'testmenu.com/CLH'),
('clh', 'Free T4', '0268', 'Free T4', 'testmenu.com/CLH'),
('clh', 'Lipid Panel', '0242', 'Lipid Panel', 'testmenu.com/CLH'),
('clh', 'HbA1c', '2712', 'Hemoglobin A1C', 'testmenu.com/CLH'),
('clh', 'Vitamin D 25-OH', '4187', '25-OH Vitamin D2 D3', 'testmenu.com/CLH'),
('clh', 'Ferritin', '0075', 'Ferritin', 'testmenu.com/CLH'),
('clh', 'Iron/TIBC', '0019', 'Iron Profile Includes TIBC Percent Saturation', 'testmenu.com/CLH'),
('clh', 'CRP', '0472', 'C Reactive Protein CRP', 'testmenu.com/CLH'),
('clh', 'hs-CRP', '1666', 'CRP C Reactive Protein Highly Sensitive', 'testmenu.com/CLH'),
('clh', 'ESR', '0382', 'ESR (Westergren)', 'testmenu.com/CLH'),
('clh', 'ANA', '2388', 'ANA RA Factor Reflex', 'testmenu.com/CLH'),
('clh', 'Testosterone Total', '4766', 'Testosterone Free and Total by Dialysis and Mass Spectrometry', 'testmenu.com/CLH'),
('clh', 'Testosterone Free', '4766', 'Testosterone Free and Total by Dialysis and Mass Spectrometry', 'testmenu.com/CLH'),
('clh', 'Estradiol', '0258', 'Estradiol', 'testmenu.com/CLH'),
('clh', 'Progesterone', '3249', 'Progesterone', 'testmenu.com/CLH'),
('clh', 'FSH', '0252', 'FSH', 'testmenu.com/CLH'),
('clh', 'LH', '0253', 'Luteinizing Hormone LH', 'testmenu.com/CLH'),
('clh', 'DHEA-S', '8018', 'DHEA Sulfate', 'testmenu.com/CLH'),
('clh', 'Prolactin', '0257', 'Prolactin', 'testmenu.com/CLH'),
('clh', 'IGF-1', '4824', 'Growth Factor I Insulin-Like (IGF-1)', 'testmenu.com/CLH'),
('clh', 'Cortisol', '2543', 'Cortisol Baseline', 'testmenu.com/CLH'),
('clh', 'Insulin', '2555', 'Insulin Fasting', 'testmenu.com/CLH'),
('clh', 'B12', '7320', 'Folate and B12', 'testmenu.com/CLH'),
('clh', 'Folate', '0076', 'Folate', 'testmenu.com/CLH'),
('clh', 'Magnesium', '0101', 'Magnesium', 'testmenu.com/CLH'),
('clh', 'Phosphorus', '0104', 'Phosphorus', 'testmenu.com/CLH'),
('clh', 'PTH', '0797', 'Parathyroid Hormone (PTH) Intact Molecule', 'testmenu.com/CLH'),
('clh', 'Calcium Ionized', '4380', 'Ionized Calcium', 'testmenu.com/CLH'),
('clh', 'Urinalysis', '0300', 'Urinalysis Complete', 'testmenu.com/CLH'),
('clh', 'Uric Acid', '0165', 'Uric Acid', 'testmenu.com/CLH'),
('clh', 'GGT', '0077', 'GGTP (GGT)', 'testmenu.com/CLH'),
('clh', 'Homocysteine', '6828', 'Homocysteine Total', 'testmenu.com/CLH'),
('clh', 'Fibrinogen', '0357', 'Fibrinogen', 'testmenu.com/CLH'),
('clh', 'PSA', '0481', 'PSA Total', 'testmenu.com/CLH'),
('clh', 'Hep B Ab', '3570', 'Hepatitis B Surface Antibody', 'testmenu.com/CLH'),
('clh', 'Hep C Ab', '0437', 'Hepatitis C Ab Reflex Quant', 'testmenu.com/CLH'),
('clh', 'HIV', '4394', 'HIV 1/2 Qualitative', 'testmenu.com/CLH'),
('clh', 'RPR', '2491', 'RPR with Reflex to Titer', 'testmenu.com/CLH'),
('clh', 'TPO Ab', '8022', 'Anti-Thyroglobulin and Anti-Thyroid Peroxidase Antibody', 'testmenu.com/CLH'),
('clh', 'Thyroglobulin Ab', '8022', 'Anti-Thyroglobulin and Anti-Thyroid Peroxidase Antibody', 'testmenu.com/CLH'),
('clh', 'Celiac', '3160', 'Celiac Dis Rfx Cascade', 'testmenu.com/CLH'),
('clh', 'Sed Rate', '0382', 'ESR (Westergren)', 'testmenu.com/CLH'),
('clh', 'Reticulocyte', '2425', 'Retic Count Automated', 'testmenu.com/CLH'),
('clh', 'Hgb Electrophoresis', '0113', 'Hemoglobin Electrophoresis', 'testmenu.com/CLH'),
('clh', 'sTfR', '1215', 'Soluble Transferrin Receptor', 'testmenu.com/CLH'),
('clh', 'Gastrin', '2816', 'Gastrin', 'testmenu.com/CLH')
ON CONFLICT (lab_id, test_name) DO UPDATE SET
  order_code = EXCLUDED.order_code,
  lab_test_name = EXCLUDED.lab_test_name,
  source = EXCLUDED.source;

-- ============================================
-- AEL — American Esoteric Laboratories
-- ============================================
INSERT INTO lab_test_codes (lab_id, test_name, order_code, lab_test_name, mnemonic, source) VALUES
('ael', 'CBC', 'H010', 'Complete Blood Count (CBC) with Differential', 'CBCD', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'CMP', 'C010', 'Comprehensive Metabolic Panel (CMP) with Estimated GFR', 'CMPGFR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'BMP', 'C011', 'Basic Metabolic Panel (BMP)', 'BMPGFR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'TSH', 'E423', 'Thyroid Stimulating Hormone (TSH)', 'TSH', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Free T3', 'E426', 'Free T3 (Free Triiodothyronine)', 'FT3', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Free T4', 'E429', 'Free T4 (Free Thyroxine)', 'FT4', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Lipid Panel', 'C014', 'Lipid Panel', 'LPP', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'HbA1c', 'C114', 'Hemoglobin A1C', 'HA1C', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Vitamin D 25-OH', 'E751', '25-Hydroxy Vitamin D', 'VD', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Ferritin', 'E278', 'Ferritin', 'FERR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Iron/TIBC', 'C133', 'Iron and Total Iron Binding Capacity (TIBC)', 'IRO', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'CRP', 'C178', 'C-Reactive Protein', 'CRP', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'hs-CRP', 'C180', 'C-Reactive Protein (CRP) High Sensitivity', 'CCRP', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'ESR', 'H214', 'Erythrocyte Sedimentation Rate (ESR)', 'ESR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'ANA', 'F226', 'Antinuclear Antibodies', 'FANA', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Testosterone Total', 'E572', 'Testosterone', 'TESTOS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Testosterone Free', 'E501', 'Testosterone Free Total LC-MS/MS', 'FTESMS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Estradiol', 'E523', 'Estradiol', 'E26III', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Progesterone', 'E548', 'Progesterone', 'BPROG', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'FSH', 'E498', 'Follicle Stimulating Hormone (FSH)', 'BFSH', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'LH', 'E538', 'Luteinizing Hormone (LH)', 'BLH', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'DHEA-S', 'E485', 'Dehydroepiandrosterone Sulfate (DHEAS)', 'DHES', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Prolactin', 'E550', 'Prolactin', 'BPRL', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'IGF-1', 'E216', 'Somatomedin-C (IGF-1)', 'SOMC', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Cortisol', 'E482', 'Cortisol', 'COR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Insulin', 'E521', 'Insulin', 'INS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'B12', 'E747', 'Vitamin B12', 'B12', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Folate', 'E736', 'Folate Serum', 'FOL', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Magnesium', 'C132', 'Magnesium', 'MAG', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Phosphorus', 'C130', 'Phosphorus', 'PHOS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'PTH', 'E188', 'Parathyroid Hormone Intact', 'PTH', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Calcium Ionized', 'E170', 'Calcium Ionized', 'ICAL', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Urinalysis', 'K004', 'Urinalysis w/Micro', 'URM', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Uric Acid', 'C191', 'Uric Acid', 'URA', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'GGT', 'C153', 'Gamma Glutamyl Transferase (GGT)', 'GGT', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Homocysteine', 'E047', 'Homocysteine', 'HCYS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Fibrinogen', 'I206', 'Fibrinogen Quantitative', 'QF', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'PSA', 'E594', 'Prostate Specific Antigen (PSA Total)', 'PSA', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Hep B Ab', 'F158', 'Hepatitis B Surface Antibody Qualitative', 'HBSB', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Hep C Ab', 'F171', 'Hepatitis C (HCV) Antibody', 'HEC', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'HIV', 'F740', 'HIV-1/2 Antigen and Antibody 4th Gen with Reflexes', 'HIVS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'RPR', 'F235', 'Rapid Plasma Reagin (RPR) Screen w/ Reflex to Titer', 'RPR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'TPO Ab', 'F803', 'Thyroid Peroxidase (TPO) Antibody', 'TPO', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Thyroglobulin Ab', 'F801', 'Anti-Thyroglobulin and Thyroid Peroxidase Ab Panel', 'THYA', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Celiac', 'CELI', 'Celiac Disease Antibody Panel', 'CELI', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Sed Rate', 'H214', 'Erythrocyte Sedimentation Rate (ESR)', 'ESR', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Reticulocyte', 'H321', 'Reticulocyte Count', 'RET', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Hgb Electrophoresis', 'E210', 'Hemoglobin Electrophoresis / HGB Fractionation', 'HEMB', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'sTfR', 'E201', 'Soluble Transferrin Receptor', 'TRS', 'testmanual.sonichealthcareusa.com/pseudoaep'),
('ael', 'Gastrin', 'E041', 'Gastrin', NULL, 'testmanual.sonichealthcareusa.com/pseudoaep')
ON CONFLICT (lab_id, test_name) DO UPDATE SET
  order_code = EXCLUDED.order_code,
  lab_test_name = EXCLUDED.lab_test_name,
  mnemonic = EXCLUDED.mnemonic,
  source = EXCLUDED.source;
