import { NextRequest, NextResponse } from 'next/server'
import { extractText } from 'unpdf'

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData()
    const file = formData.get('file') as File | null
    if (!file) return NextResponse.json({ error: 'No file provided' }, { status: 400 })

    const buffer = await file.arrayBuffer()
    console.log(`PDF upload: file=${file.name} size=${file.size} type=${file.type}`)

    const { text, totalPages } = await extractText(new Uint8Array(buffer), { mergePages: true })
    console.log(`PDF extract: pages=${totalPages} textLength=${text?.length ?? 0} preview=${text?.slice(0, 200)}`)

    if (!text || text.trim().length === 0) {
      return NextResponse.json({ error: 'No text found in PDF — it may be image-based or generated by an EMR system that embeds content as images' }, { status: 422 })
    }

    return NextResponse.json({ text: text.trim() })
  } catch (e) {
    console.error('PDF text extract error:', e)
    return NextResponse.json({ error: `Failed to extract PDF text: ${e instanceof Error ? e.message : 'unknown'}` }, { status: 500 })
  }
}
