/**
 * Test Bundles — curated panels for common patient needs.
 * These are NOT database entities; they're editorial groupings
 * that help users understand which tests to order together.
 *
 * Each bundle maps to real test_name values in the DB.
 */

export type TestBundle = {
  slug: string
  name: string
  shortName: string
  icon: string
  category: 'hormones' | 'thyroid-energy' | 'nutrition' | 'wellness'
  description: string
  whoNeeds: string
  tests: string[]  // test_name values (must match DB exactly)
  notes?: string
}

export const TEST_BUNDLES: TestBundle[] = [
  {
    slug: 'thyroid-complete',
    name: 'Thyroid Complete Panel',
    shortName: 'Thyroid Complete',
    icon: '🦋',
    category: 'thyroid-energy',
    description: 'The full thyroid picture — not just TSH. Includes free hormones, antibodies, and reverse T3 for a complete assessment.',
    whoNeeds: 'Anyone with thyroid symptoms, Hashimoto\'s, Graves\' disease, or on thyroid medication. Hypothyroid symptoms include fatigue, weight gain, brain fog, hair loss, and feeling cold. Hyperthyroid symptoms include weight loss, anxiety, palpitations, heat intolerance, and tremors.',
    tests: [
      'TSH (Thyroid Stimulating Hormone)',
      'Free T4 (Thyroxine, Free)',
      'Free T3 (Triiodothyronine, Free)',
      'Reverse T3 (rT3)',
      'Anti-TPO (Thyroid Peroxidase Antibody)',
      'Anti-Thyroglobulin Antibody (TgAb)',
    ],
    notes: 'Most doctors only check TSH. If you\'re symptomatic but TSH is "normal," Free T3 and antibodies often reveal the real problem.',
  },
  {
    slug: 'hormone-baseline',
    name: 'Hormone Baseline Panel (Female)',
    shortName: 'Hormone Baseline',
    icon: '🌸',
    category: 'hormones',
    description: 'Baseline hormone panel before starting bioidentical hormone replacement therapy. Establishes your starting point for estrogen, progesterone, testosterone, and supporting markers.',
    whoNeeds: 'Women considering or starting BHRT, perimenopause, or menopause hormone therapy. Also useful if you\'re experiencing fatigue, low libido, mood changes, or other hormonal symptoms without a clear cause. And worth considering for women who feel well — knowing your optimal now gives you a reference point for the future.',
    tests: [
      'Estradiol (E2)',
      'Progesterone',
      'Testosterone, Total',
      'Testosterone, Free (Calculated)',
      'SHBG (Sex Hormone Binding Globulin)',
      'DHEA-Sulfate (DHEA-S)',
      'FSH (Follicle Stimulating Hormone)',
      'LH (Luteinizing Hormone)',
      'Cortisol, AM (Serum)',
      'CBC with Differential (CBC w/ Diff)',
      'CMP (Comprehensive Metabolic Panel)',
    ],
    notes: 'Get this panel BEFORE starting hormones so you have a true baseline. Retest at 6-8 weeks after starting, then every 3-6 months.',
  },
  {
    slug: 'trt-monitoring',
    name: 'TRT Monitoring Panel (Male)',
    shortName: 'TRT Monitoring',
    icon: '💪',
    category: 'hormones',
    description: 'Essential monitoring labs for men on testosterone replacement therapy. Tracks hormone levels, red blood cell count, and organ function.',
    whoNeeds: 'Men currently on TRT or considering it. Should be run before starting, at 6-8 weeks, then every 3-6 months.',
    tests: [
      'Testosterone, Total',
      'Testosterone, Free (Calculated)',
      'Estradiol (E2)',
      'SHBG (Sex Hormone Binding Globulin)',
      'LH (Luteinizing Hormone)',
      'FSH (Follicle Stimulating Hormone)',
      'Prolactin',
      'PSA (Prostate-Specific Antigen)',
      'CBC with Differential (CBC w/ Diff)',
      'CMP (Comprehensive Metabolic Panel)',
      'Lipid Panel (Standard)',
      'HbA1c (Hemoglobin A1c)',
    ],
    notes: 'Watch hematocrit on TRT — if it climbs above 54%, discuss with your provider. Estradiol management is key to avoiding side effects.',
  },
  {
    slug: 'pcos-panel',
    name: 'PCOS Support Panel',
    shortName: 'PCOS Support',
    icon: '🎀',
    category: 'hormones',
    description: 'Comprehensive panel for diagnosing and monitoring polycystic ovary syndrome. Covers hormones, insulin resistance, and commonly missed markers.',
    whoNeeds: 'Women with suspected or diagnosed PCOS, fertility challenges, or hormonal symptoms like irregular periods, acne, facial hair, thinning hair, skin changes, or unexplained weight gain.',
    tests: [
      'Testosterone, Total',
      'Testosterone, Free (Calculated)',
      'DHEA-Sulfate (DHEA-S)',
      'SHBG (Sex Hormone Binding Globulin)',
      'LH (Luteinizing Hormone)',
      'FSH (Follicle Stimulating Hormone)',
      'Estradiol (E2)',
      'Progesterone',
      'AMH (Anti-Mullerian Hormone)',
      'Insulin, Fasting',
      'Glucose, Fasting',
      'HbA1c (Hemoglobin A1c)',
      'Prolactin',
      'Progesterone, 17-OH (17-Hydroxyprogesterone)',
      'Free T3 (Triiodothyronine, Free)',
      'TSH (Thyroid Stimulating Hormone)',
    ],
    notes: 'LH:FSH ratio > 2:1 is a classic PCOS finding but not required for diagnosis. Insulin resistance is present in ~70% of PCOS cases even at normal weight.',
  },
  {
    slug: 'iron-deep-dive',
    name: 'Iron & Anemia Deep Dive',
    shortName: 'Iron Deep Dive',
    icon: '🩸',
    category: 'nutrition',
    description: 'Goes beyond basic iron to find the root cause of anemia or iron issues. Includes storage, transport, and production markers.',
    whoNeeds: 'Anyone with low ferritin, heavy periods, or unexplained low iron despite supplementation. Common anemia symptoms include fatigue, brain fog, hair loss, shortness of breath, dizziness, and pale skin.',
    tests: [
      'Ferritin',
      'Iron, Serum',
      'TIBC (Total Iron Binding Capacity)',
      'Transferrin Saturation',
      'CBC with Differential (CBC w/ Diff)',
      'Reticulocyte Count',
      'Vitamin B12 (Cobalamin)',
      'Folate, Serum',
      'Haptoglobin',
    ],
    notes: 'Ferritin is the most important single marker. Optimal is 50-150 for women — many labs flag "normal" at 12+, which is NOT optimal. If ferritin is low despite supplementation, check for absorption issues or occult bleeding.',
  },
  {
    slug: 'preventive-health',
    name: 'Preventive Health Panel',
    shortName: 'Preventive Health',
    icon: '🧬',
    category: 'wellness',
    description: 'The comprehensive annual panel for catching what your doctor might miss. Covers metabolic health, cardiovascular risk, inflammation, and key nutrients.',
    whoNeeds: 'Adults who want thorough annual bloodwork beyond the standard checkup. Especially if you have a family history of heart disease, diabetes, or autoimmune conditions. Also a strong choice for optimizers and health-focused individuals who want to know their numbers while they feel their best — not just when something goes wrong.',
    tests: [
      'CBC with Differential (CBC w/ Diff)',
      'CMP (Comprehensive Metabolic Panel)',
      'Lipid Panel (Standard)',
      'Apolipoprotein B (ApoB)',
      'Lipoprotein(a) [Lp(a)]',
      'HbA1c (Hemoglobin A1c)',
      'Insulin, Fasting',
      'hs-CRP (High Sensitivity CRP)',
      'Homocysteine',
      'Vitamin D, 25-OH (Total)',
      'Ferritin',
      'TSH (Thyroid Stimulating Hormone)',
      'Free T3 (Triiodothyronine, Free)',
      'DHEA-Sulfate (DHEA-S)',
      'GGT (Gamma-Glutamyl Transferase)',
      'Uric Acid',
    ],
    notes: 'ApoB is increasingly considered a better predictor of cardiovascular risk than LDL alone. Fasting insulin catches metabolic issues years before glucose or A1c go out of range.',
  },
  {
    slug: 'energy-fatigue',
    name: 'Energy & Fatigue Panel',
    shortName: 'Energy & Fatigue',
    icon: '⚡',
    category: 'thyroid-energy',
    description: 'The "why am I so tired?" panel. Covers the most common — and commonly missed — causes of fatigue: iron, thyroid, blood sugar, hormones, and key nutrients.',
    whoNeeds: 'Anyone dealing with persistent fatigue, brain fog, low motivation, or energy crashes that don\'t improve with sleep.',
    tests: [
      'Ferritin',
      'Iron, Serum',
      'TIBC (Total Iron Binding Capacity)',
      'CBC with Differential (CBC w/ Diff)',
      'TSH (Thyroid Stimulating Hormone)',
      'Free T3 (Triiodothyronine, Free)',
      'Free T4 (Thyroxine, Free)',
      'Vitamin B12 (Cobalamin)',
      'Folate, Serum',
      'Vitamin D, 25-OH (Total)',
      'HbA1c (Hemoglobin A1c)',
      'Cortisol, AM (Serum)',
      'Magnesium, Serum',
      'CMP (Comprehensive Metabolic Panel)',
    ],
    notes: 'Ferritin under 50 causes fatigue in many people — even when labs say "normal" at 12+. Thyroid is the second most common miss. Always test Free T3, not just TSH — you can have a normal TSH with low T3 and still feel terrible.',
  },
  {
    slug: 'gut-health',
    name: 'Gut Health Panel',
    shortName: 'Gut Health',
    icon: '🫁',
    category: 'nutrition',
    description: 'Tests for common gut issues including celiac, H. pylori, inflammation, and malabsorption markers. Pairs well with the Nutrient Deficiencies panel.',
    whoNeeds: 'People with chronic bloating, IBS symptoms, food sensitivities, fatigue, unexplained nutrient deficiencies, or suspected celiac/SIBO.',
    tests: [
      'H. Pylori Antibody (IgG)',
      'Fecal Calprotectin',
      'hs-CRP (High Sensitivity CRP)',
      'ESR (Erythrocyte Sedimentation Rate)',
      'CMP (Comprehensive Metabolic Panel)',
      'Vitamin B12 (Cobalamin)',
      'Ferritin',
      'Vitamin D, 25-OH (Total)',
      'Folate, Serum',
      'Magnesium, Serum',
    ],
    notes: 'If you have chronic GI symptoms, start with celiac and H. pylori — both are common and treatable. Low ferritin, B12, or vitamin D with no obvious cause often points to a gut absorption issue.',
  },
  {
    slug: 'nutrient-deficiencies',
    name: 'Nutrient Deficiencies Panel',
    shortName: 'Nutrient Deficiencies',
    icon: '💊',
    category: 'nutrition',
    description: 'Checks the nutrients most commonly depleted in modern diets and chronic illness. Many of these are missed in standard bloodwork.',
    whoNeeds: 'Anyone with fatigue, hair loss, brain fog, muscle cramps, mood changes, or on medications that deplete nutrients (PPIs, metformin, birth control).',
    tests: [
      'Ferritin',
      'Vitamin D, 25-OH (Total)',
      'Vitamin B12 (Cobalamin)',
      'Folate, Serum',
      'Magnesium, Serum',
      'Zinc, Serum',
      'Selenium, Serum',
      'Iron, Serum',
      'TIBC (Total Iron Binding Capacity)',
      'Transferrin Saturation',
      'Copper, Serum',
      'CBC with Differential (CBC w/ Diff)',
    ],
    notes: 'PPIs deplete B12, magnesium, and iron. Metformin depletes B12. Birth control depletes B6, folate, and zinc. If you\'re on any of these long-term, check these regularly.',
  },
  {
    slug: 'cycle-health',
    name: 'Cycle Health & Fertility Baseline',
    shortName: 'Cycle Health',
    icon: '🌙',
    category: 'hormones',
    description: 'Hormone panel for understanding your menstrual cycle, investigating irregular periods, or establishing a fertility baseline. Timing matters — see notes.',
    whoNeeds: 'Women with irregular cycles, heavy periods, trying to conceive, or wanting to understand their hormonal health.',
    tests: [
      'FSH (Follicle Stimulating Hormone)',
      'LH (Luteinizing Hormone)',
      'Estradiol (E2)',
      'Progesterone',
      'AMH (Anti-Mullerian Hormone)',
      'Prolactin',
      'TSH (Thyroid Stimulating Hormone)',
      'Free T3 (Triiodothyronine, Free)',
      'Testosterone, Total',
      'DHEA-Sulfate (DHEA-S)',
      'CBC with Differential (CBC w/ Diff)',
      'Ferritin',
      'Vitamin D, 25-OH (Total)',
    ],
    notes: 'Timing is critical: FSH, LH, and estradiol on cycle day 2-4 (early follicular). Progesterone on day 19-22 (mid-luteal, ~7 days post-ovulation). AMH can be drawn anytime. If cycles are irregular, your provider may adjust timing.',
  },
  {
    slug: 'inflammation-immune',
    name: 'Inflammation & Immune Health Panel',
    shortName: 'Inflammation/Immunity',
    icon: '🔬',
    category: 'wellness',
    description: 'Screens for systemic inflammation and autoimmune markers. Useful for investigating unexplained symptoms, joint pain, or family history of autoimmune disease.',
    whoNeeds: 'Anyone with unexplained joint pain, rashes, fatigue, or family history of lupus, RA, Hashimoto\'s, or other autoimmune conditions.',
    tests: [
      'ANA (Antinuclear Antibody) Screen, IFA',
      'hs-CRP (High Sensitivity CRP)',
      'ESR (Erythrocyte Sedimentation Rate)',
      'Complement C3',
      'Complement C4',
      'Rheumatoid Factor (RF)',
      'Anti-CCP (Cyclic Citrullinated Peptide)',
      'CBC with Differential (CBC w/ Diff)',
      'CMP (Comprehensive Metabolic Panel)',
      'Ferritin',
      'Vitamin D, 25-OH (Total)',
      'Anti-TPO (Thyroid Peroxidase Antibody)',
    ],
    notes: 'A positive ANA alone does not mean you have lupus — up to 15% of healthy people are ANA positive. Pattern and titer matter. hs-CRP + ESR together give a better picture of inflammation than either alone.',
  },
  {
    slug: 'bhrt-monitoring',
    name: 'BHRT Monitoring Panel (Female)',
    shortName: 'BHRT Monitoring',
    icon: '🌺',
    category: 'hormones',
    description: 'Ongoing monitoring panel for women on bioidentical hormone replacement therapy. Tracks hormone levels, thyroid, metabolic markers, and safety labs.',
    whoNeeds: 'Women currently on BHRT, pellets, creams, or patches. Run every 3-6 months or when adjusting doses.',
    tests: [
      'Estradiol (E2)',
      'Progesterone',
      'Testosterone, Total',
      'Testosterone, Free (Calculated)',
      'SHBG (Sex Hormone Binding Globulin)',
      'DHEA-Sulfate (DHEA-S)',
      'Free T3 (Triiodothyronine, Free)',
      'TSH (Thyroid Stimulating Hormone)',
      'Cortisol, AM (Serum)',
      'CBC with Differential (CBC w/ Diff)',
      'CMP (Comprehensive Metabolic Panel)',
      'Lipid Panel (Standard)',
      'Vitamin D, 25-OH (Total)',
      'Ferritin',
    ],
    notes: 'Test estradiol and progesterone at trough (right before next dose/application). If on pellets, test at ~4-6 weeks post-insertion for peak, then again at 10-12 weeks. Always include thyroid — hormones affect conversion.',
  },
  {
    slug: 'weight-metabolism',
    name: 'Weight & Metabolism Panel',
    shortName: 'Weight & Metabolism',
    icon: '⚖️',
    category: 'nutrition',
    description: 'The "why can\'t I lose weight?" panel. Covers insulin resistance, thyroid function, cortisol, and metabolic markers that are often missed in standard bloodwork.',
    whoNeeds: 'Anyone struggling with unexplained weight gain, weight loss resistance, fatigue, or other metabolic symptoms despite diet and exercise changes.',
    tests: [
      'Insulin, Fasting',
      'Glucose, Fasting',
      'HbA1c (Hemoglobin A1c)',
      'TSH (Thyroid Stimulating Hormone)',
      'Free T3 (Triiodothyronine, Free)',
      'Free T4 (Thyroxine, Free)',
      'Reverse T3 (rT3)',
      'Cortisol, AM (Serum)',
      'DHEA-Sulfate (DHEA-S)',
      'Testosterone, Total',
      'Estradiol (E2)',
      'Lipid Panel (Standard)',
      'hs-CRP (High Sensitivity CRP)',
      'Vitamin D, 25-OH (Total)',
      'Ferritin',
      'Uric Acid',
    ],
    notes: 'Fasting insulin is the single most underordered test. Most doctors check glucose and A1c but miss insulin — which can be elevated for YEARS before glucose goes out of range. If your fasting insulin is above 8-10, you likely have insulin resistance regardless of what your glucose says.',
  },
  {
    slug: 'mood-brain-health',
    name: 'Mood & Brain Health Panel',
    shortName: 'Mood & Brain Health',
    icon: '🧠',
    category: 'wellness',
    description: 'Key biomarkers linked to mood, cognition, and mental health. Many mood disorders have underlying nutritional or hormonal causes that go untested.',
    whoNeeds: 'Anyone experiencing depression, anxiety, fatigue, brain fog, poor focus, or mood swings — especially if standard treatments haven\'t fully worked. Also useful for anyone on psychiatric medication who wants a fuller picture.',
    tests: [
      'Vitamin D, 25-OH (Total)',
      'Vitamin B12 (Cobalamin)',
      'Folate, Serum',
      'Ferritin',
      'TSH (Thyroid Stimulating Hormone)',
      'Free T3 (Triiodothyronine, Free)',
      'Magnesium, RBC',
      'Cortisol, AM (Serum)',
      'DHEA-Sulfate (DHEA-S)',
      'Homocysteine',
      'Insulin, Fasting',
      'HbA1c (Hemoglobin A1c)',
      'Zinc, Serum',
      'Omega-3 Index',
    ],
    notes: 'Low vitamin D, B12, ferritin, and magnesium are some of the most common — and most treatable — contributors to mood and cognitive symptoms. If your doctor says "your labs are normal" but only checked a CBC and CMP, these are the tests they likely missed.',
  },
]
