'use client'

import { useState, useCallback, useRef } from 'react'

export default function FormatPage() {
  const [rawInput, setRawInput] = useState('')
  const [formatted, setFormatted] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isPdfLoading, setIsPdfLoading] = useState(false)
  const [pdfError, setPdfError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const pdfInputRef = useRef<HTMLInputElement>(null)
  const outputRef = useRef<HTMLDivElement>(null)

  const handlePdfUpload = useCallback(async (file: File) => {
    setPdfError(null)
    if (!file) return
    if (!file.name.toLowerCase().endsWith('.pdf')) {
      setPdfError(`File "${file.name}" doesn't look like a PDF.`)
      return
    }
    setIsPdfLoading(true)
    try {
      const formData = new FormData()
      formData.append('file', file)
      const res = await fetch('/api/extract-pdf-text', { method: 'POST', body: formData })
      const json = await res.json()
      if (res.status === 422) {
        setPdfError("This PDF doesn't contain selectable text — it may be image-based or generated by an EMR system. Try copying and pasting your results directly.")
        setIsPdfLoading(false)
        return
      }
      if (!res.ok) throw new Error(json.error || `Server error ${res.status}`)
      if (!json.text) throw new Error('No text extracted')
      setRawInput(prev => prev ? prev + '\n' + json.text.trim() : json.text.trim())
      setFormatted('')
    } catch (e) {
      setPdfError(`Could not read PDF: ${e instanceof Error ? e.message : 'unknown error'}.`)
    }
    setIsPdfLoading(false)
  }, [])

  const handleFormat = async () => {
    if (!rawInput.trim()) return
    setIsLoading(true)
    setError(null)
    setFormatted('')
    try {
      const res = await fetch('/api/format-labs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: rawInput }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error || `Server error ${res.status}`)
      setFormatted(json.formatted)
      setTimeout(() => outputRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50)
    } catch (e) {
      setError(`Something went wrong: ${e instanceof Error ? e.message : 'unknown error'}`)
    }
    setIsLoading(false)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatted)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback
      const el = document.createElement('textarea')
      el.value = formatted
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleReset = () => {
    setRawInput('')
    setFormatted('')
    setError(null)
    setPdfError(null)
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#faf8f5' }}>
      <div className="max-w-3xl mx-auto px-4 pt-24 pb-12">

        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="text-3xl md:text-4xl font-bold text-[#1a2e2b] mb-3">
            Format labs for sharing
          </h1>
          <p className="text-lg" style={{ color: '#4a6b67' }}>
            Paste messy lab results — get a clean, readable format perfect for patient groups.
          </p>
        </div>

        {/* Input card */}
        <div className="bg-white rounded-xl shadow-sm border p-6 mb-4" style={{ borderColor: '#e0ebe9' }}>
          <div className="flex items-center justify-between mb-3">
            <label className="block text-sm font-semibold" style={{ color: '#1a2e2b' }}>
              Paste your raw lab results
            </label>
            <div className="flex items-center gap-2">
              {(rawInput || formatted) && (
                <button
                  onClick={handleReset}
                  className="text-xs px-2 py-1 rounded-lg transition-all"
                  style={{ backgroundColor: '#fef2f2', color: '#991b1b', border: '1px solid #fecaca' }}
                >
                  ↺ Start over
                </button>
              )}
              <button
                onClick={() => pdfInputRef.current?.click()}
                disabled={isPdfLoading}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
                style={{ backgroundColor: '#f0f7f6', color: '#2d6a5e', border: '1px solid #c5deda' }}
              >
                {isPdfLoading ? '⏳ Reading PDF...' : '📄 Upload PDF'}
              </button>
              <input
                ref={pdfInputRef}
                type="file"
                accept=".pdf,application/pdf"
                className="hidden"
                onChange={(e) => { const f = e.target.files?.[0]; if (f) handlePdfUpload(f); e.target.value = '' }}
              />
            </div>
          </div>

          {pdfError && (
            <div className="mb-3 px-3 py-2 rounded-lg text-xs" style={{ backgroundColor: '#fef2f2', color: '#991b1b', border: '1px solid #fecaca' }}>
              ⚠️ {pdfError}
            </div>
          )}

          <textarea
            value={rawInput}
            onChange={(e) => { setRawInput(e.target.value); setFormatted('') }}
            placeholder={`Paste your lab results here — any format works.\n\nExample:\nFree T3 2.5 (2.0-4.4) pg/mL\nFerritin 54 ng/mL [12-150]\nTSH: 1.82 mIU/L ref 0.40-4.50`}
            rows={8}
            className="w-full px-4 py-3 rounded-lg border-2 border-[#2d6a5e] text-sm text-[#1a2e2b] placeholder-[#577572] bg-white resize-y focus:outline-none focus:ring-2 focus:ring-[#2d6a5e]/30 transition-colors"
          />

          {error && (
            <div className="mt-3 px-3 py-2 rounded-lg text-xs" style={{ backgroundColor: '#fef2f2', color: '#991b1b', border: '1px solid #fecaca' }}>
              ⚠️ {error}
            </div>
          )}

          <div className="flex items-center justify-between mt-3">
            <p className="text-xs" style={{ color: '#9ca3af' }}>Works with Quest, LabCorp, CPL, and most portal exports</p>
            <button
              onClick={handleFormat}
              disabled={!rawInput.trim() || isLoading}
              className="px-5 py-2 rounded-lg text-sm font-semibold transition-all"
              style={{
                backgroundColor: rawInput.trim() && !isLoading ? '#2d6a5e' : '#e0ebe9',
                color: rawInput.trim() && !isLoading ? 'white' : '#577572',
                cursor: rawInput.trim() && !isLoading ? 'pointer' : 'not-allowed',
              }}
            >
              {isLoading ? '✨ Formatting...' : 'Format →'}
            </button>
          </div>
        </div>

        {/* Output card */}
        {formatted && (
          <div ref={outputRef} className="bg-white rounded-xl shadow-sm border p-6 mb-6" style={{ borderColor: '#e0ebe9' }}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-bold" style={{ color: '#1a2e2b' }}>Ready to share</h2>
              <button
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all"
                style={{
                  backgroundColor: copied ? '#f0fdf4' : '#2d6a5e',
                  color: copied ? '#15803d' : 'white',
                  border: copied ? '1px solid #bbf7d0' : 'none',
                }}
              >
                {copied ? '✓ Copied!' : '📋 Copy'}
              </button>
            </div>

            {/* Formatted output — monospace-ish, readable */}
            <div
              className="rounded-lg p-4 text-sm leading-relaxed whitespace-pre-wrap font-mono"
              style={{
                backgroundColor: '#f8faf9',
                border: '1px solid #e0ebe9',
                color: '#1a2e2b',
                fontFamily: '"SF Mono", "Fira Code", "Courier New", monospace',
                fontSize: '13px',
                lineHeight: '1.7',
              }}
            >
              {formatted}
            </div>

            <div className="mt-4 flex items-center justify-between">
              <p className="text-xs" style={{ color: '#9ca3af' }}>
                Plain text — safe to paste into Facebook, Reddit, or any patient group
              </p>
              <button
                onClick={handleCopy}
                className="text-xs px-3 py-1.5 rounded-lg transition-all"
                style={{ backgroundColor: copied ? '#f0fdf4' : '#f0f7f6', color: copied ? '#15803d' : '#2d6a5e', border: `1px solid ${copied ? '#bbf7d0' : '#c5deda'}` }}
              >
                {copied ? '✓ Copied!' : '📋 Copy again'}
              </button>
            </div>
          </div>
        )}

        {/* How it works / empty state */}
        {!formatted && (
          <div className="mt-6">
            <div className="rounded-xl border border-[#e0ebe9] bg-white p-6">
              <div className="grid gap-5 sm:grid-cols-3">
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider text-[#2d6a5e] mb-2">What to paste</div>
                  <p className="text-sm text-[#4a6b67] leading-relaxed">
                    Raw lab results from any portal — Quest MyQuest, LabCorp Patient, your doctor&apos;s PDF, or just text you copied.
                  </p>
                </div>
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider text-[#2d6a5e] mb-2">What you get</div>
                  <p className="text-sm text-[#4a6b67] leading-relaxed">
                    Clean ALL CAPS test names, values, H/L flags, reference ranges in parentheses — ready to paste into any group.
                  </p>
                </div>
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider text-[#2d6a5e] mb-2">Example output</div>
                  <p className="text-sm font-mono leading-relaxed" style={{ color: '#1a2e2b', fontSize: '12px' }}>
                    FREE T3: 2.5 (L)<br />
                    (ref: 2.0–4.4 pg/mL)<br />
                    <br />
                    TSH: 1.82<br />
                    (ref: 0.4–4.5 mIU/L)
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <div className="mt-6 rounded-lg p-4 text-xs" style={{ backgroundColor: '#fff8f5', border: '1px solid #e8d5cc', color: '#4a6b67' }}>
          <p>
            <strong style={{ color: '#b85c5c' }}>For informational use only.</strong>{' '}
            LabLooker does not store your lab results. This tool formats for readability — it does not provide medical advice or diagnosis. Always discuss your results with your healthcare provider.
          </p>
        </div>

      </div>
    </div>
  )
}
